version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8888:80
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      - ./:/var/www/html/wp-content/plugins/wp-granular-demo:rw

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    ports:
      - 8889:8080
    restart: "no"
